### ISSUE TITLE
unique combinations when using duplicate letters/elements

### ISSUE THREAD

**Issue by wivaku** [bpolaszek/string-combinations#1]
Using `string_combinations('aba', $min=3)->withoutDuplicates()->asArray()`
Note: `a` appears twice.

Result: `aba aab baa baa aab aba`

Would like to get: `aba aab baa` (so: no duplicates)
I can use `array_unique()` but was hoping `string_combinations()` could avoid them in the first place.

**Comment by bpolaszek** [comment]
Hi @wivaku,

First argument of string_combinations() expect unduplicated values (you have "a" twice).

**Comment by wivaku** [comment]
Understood. In my case I do have duplicates. I want the unique combinations of 2x Apple and 1x Orange.

**Comment by bpolaszek** [comment]
Then you'll have to unduplicate them by yourself with `array_unique`.
This library uses generators to generate combinations to keep the memory usage low; keeping in memory the already yielded values to prevent duplicates would be counterproductive.

**Comment by wivaku** [comment]
Ok, thanks. That's indeed what I was using.
